email:
  config:
    port: "587"
    host: "smtp.gmail.com"
    user: "ayal.aboze@gmail.com"
    password: "sakflebkevvhlfgn"
http:
  host: "localhost"
  port: "8081"    
db:
  port: "3306"
  host: "localhost"
  user: "root" 
  password: "Harar1350" 
  database: "mulerealtime"
